=begin
#CryptoAPIs

#Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

The version of the OpenAPI document: 2.0.0
Contact: developers@cryptoapis.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::GetTransactionDetailsByTransactionIDResponseItemBlockchainSpecificLitecoinScriptSig
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::GetTransactionDetailsByTransactionIDResponseItemBlockchainSpecificLitecoinScriptSig do
  let(:instance) { OpenapiClient::GetTransactionDetailsByTransactionIDResponseItemBlockchainSpecificLitecoinScriptSig.new }

  describe 'test an instance of GetTransactionDetailsByTransactionIDResponseItemBlockchainSpecificLitecoinScriptSig' do
    it 'should create an instance of GetTransactionDetailsByTransactionIDResponseItemBlockchainSpecificLitecoinScriptSig' do
      expect(instance).to be_instance_of(OpenapiClient::GetTransactionDetailsByTransactionIDResponseItemBlockchainSpecificLitecoinScriptSig)
    end
  end
  describe 'test attribute "asm"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "hex"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
